// import type { Metadata } from "next";
// import ClientSessionWrapper from './ClientSessionWrapper'; // Client Component
// import localFont from "next/font/local";
// import Link from "next/link";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ul className="flex bg-blue-600 mb-4 pl-2">
//           <li className="block px-4 py-2 my-1 hover:bg-gray-100 rounded">
//             <Link className="no-underline text-blue-300" href="/">
//               Home</Link></li>
//           <li className="block text-blue-300 px-4 py-2 my-1 hover:bg-gray-100 rounded">
//             <Link className="no-underline text-blue-300" href="/insights">
//               Insights</Link></li>
//           <li className="block text-blue-300 px-4 py-2 my-1 hover:bg-gray-100 rounded">
//             <Link className="no-underline text-blue-300" href="/recommends">
//               Recommends</Link></li>
//           <li className="block text-blue-300 px-4 py-2 my-1 hover:bg-gray-100 rounded">
//             <Link className="no-underline text-blue-300" href="/playlists">
//               Playlists</Link></li>
//           <li className="block text-blue-300 px-4 py-2 my-1 hover:bg-gray-100 rounded">
//             <Link className="no-underline text-blue-300" href="/login">
//               Login</Link></li>
//         </ul>
//         {/* {children} */}
//         {/* Client-side wrapper for session logic */}
//         <ClientSessionWrapper>{children}</ClientSessionWrapper>
//       </body>
//     </html>
//   );
// }

'use client';

import { SessionProvider } from "next-auth/react";
import Link from "next/link";
import Header from './components/Header';
import "./globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <SessionProvider>
      <html lang="en">
        <body>
          <Header />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}